### ISSUE TITLE
Demo not loading.

### ISSUE THREAD

**Issue by zerkman** [zerkman/zest#11]
Several demos are stuck at some point. They usually start one first intro screen, then get blocked.
Demos with that problem include:
 - ~~dark side of the spoon~~
 - ~~o-demo~~
 - ~~odd stuff~~
 - ~~ooh crikey wot a scorcher~~
 - ~~decade demo~~
 - ~~dothings~~
 - ~~my socks are weapons~~

**Comment by zerkman** [comment]
dothings : very slow to load first part, then not loading second part. could be two different bugs

**Comment by zerkman** [comment]
ooh crikey and dark side have been fixed by 5746886eebbf883c4b2952ab45a7b462a30e0d12.

**Comment by zerkman** [comment]
odd stuff has been fixed by 6a0f3e019afd73ba2737e93fa862500c05db68cb.

**Comment by Gunstick** [comment]
This is a known "feature" of the ST. If you deselect the floppy while the motor is still spinning, it won't stop spinning. The OS specifically waits for the motor to stop by polling the floppy, and then only deselects the floppy (light goes off). These demos use this behavior to have the floppy still spin for the next track to load, so there is no spinup delay.

**Comment by zerkman** [comment]
I know it worked like this at the time, and I did not understand the mechanisms involved. What makes the WD1772 stop the drive is the detection of 9 index pulses (corresponding to 9 rotations of the disk) after running the last command. If the drive is de-selected before that, the WD1772 does not "see" these index pulses because the drive I/O is somehow electrically disconnected.

What fixed ooh crikey and dark side was another problem. It seems you don't have to enable the "motor on" flag in your FDC commands to get the motor actually turn on. It will turn on anyway. I removed some flag checks and now every command actually checks if the drive is on, undepending on the status of the motor on flag.

**Comment by zerkman** [comment]
Decade demo: the intro runs, then the 9 to 0 countdown, and then the screen goes all red. The demo remains stuck at that point.

**Comment by zerkman** [comment]
o-demo, decade demo, and probably others have been fixed by 5e28fea740f58a3832d6d2a72ac45eefc222933c and b100c0970def09d1482ece0c2ac87270f27deba0.

dothings is fixed too, not sure whether by this set of commits or older ones.

**Comment by zerkman** [comment]
"My socks are weapons" has been fixed by 58224aacb2742078a2d794d6d63c88365b95160b and b42e80b961835f7fb81952d52e1572a09a1f8a8e.

**Comment by zerkman** [comment]
Since all the above demos loading problems have been fixed, let's close the issue. We still can create another when we meet new issues.
