### ISSUE TITLE
Tex Demos don't work

### ISSUE THREAD

**Issue by matt-grain** [zerkman/zest#18]
Tex demo 1 and 2 from POV disk 3
disk: https://www.planetemu.net/rom/atari-st-compilations-demos/persistance-of-vision-003-1989-pov-2

Sound is ok but display is wrong (fullscreen?)

**Comment by zerkman** [comment]
I tested with the recent version of zeST, the demo screens seem to be working as expected. There are no fullscreen techniques involved in them.
