### ISSUE TITLE
Build fails in 'linux' folder

### ISSUE THREAD

**Issue by ggnkua** [zerkman/zest#2]
```
/home/ggn/zest/linux/setup.c:171: undefined reference to `pthread_create'
/usr/bin/ld: /home/ggn/zest/linux/setup.c:173: undefined reference to `pthread_create'
/usr/bin/ld: /home/ggn/zest/linux/setup.c:192: undefined reference to `pthread_join'
/usr/bin/ld: /home/ggn/zest/linux/setup.c:193: undefined reference to `pthread_join'
collect2: error: ld returned 1 exit status
make: *** [Makefile:26: zeST] Error 1
```

Adding ```-lpthread``` to the Makefile fixed this:

https://github.com/zerkman/zest/blob/e048e3591176faa2ce5af4f4580a64b266dcc492/linux/Makefile#L25-L26

**Comment by zerkman** [comment]
Seems you are building for your host machine. There is no need for -lpthread in uClibc-ng.

are you sure you are using buildroot's cross-compiler toolchain ?

For the toolchain to work I'm using these environment configs before running make:

    export PATH=$HOME/src/buildroot-2020.05/output/host/bin:$PATH
    export CC=arm-buildroot-linux-uclibcgnueabihf-gcc

**Comment by ggnkua** [comment]
Just tried that really quick and I can confirm it works ok here :)
