### ISSUE TITLE
Lockup on zui libray

### ISSUE THREAD

**Issue by ggnkua** [zerkman/zest#8]
This troubled me for a long time but I couldn't find the exact cause. Finally I found it: When entering a new form if the user presses shift-tab (or up) then the menu enters an infinite loop when calling prev_focusable().

[zui.zip](https://github.com/zerkman/zest/files/9453646/zui.zip)

The attached patch fixes this by making the first focusable item selected on form startup. Not sure if there is a more elegant way to do this but it works at least :)

**Comment by zerkman** [comment]
(months later) thanks, I guess since that time the fix has been integrated in the master branch.
